sequences:
  DLH: workflow/PDEFinder/Data/FASTA/DLH/A0A1H6AD45_AA.fasta
  LCC: workflow/PDEFinder/Data/FASTA/LCC/G9BY57_AA.fasta
  MNP1: workflow/PDEFinder/Data/FASTA/MNP1/Q02567_AA.fasta
  rubredoxin: workflow/PDEFinder/Data/FASTA/rubredoxin/Q9HTK9_AA.fasta
  soybean: workflow/PDEFinder/Data/FASTA/soybean/O22443_AA.fasta

query: "workflow/Data/FASTA/DataBases/familiesDB.fasta"

upi_database: "workflow/Data/FASTA/literature_seq/lit_sequences.fasta"

thresholds: ["60-65", "65-70", "70-75", "75-80", "80-85", "85-90"]


# clusters:
# fazer função para retirar os numeros de cada cluster por cada threshold?